# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "pal_async_test"
edition = "2021"
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = [ "full" ] }

[lints]
workspace = true
