# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "scsi_buffers"
edition = "2021"
rust-version.workspace = true

[dependencies]
guestmem.workspace = true
safeatomic.workspace = true

smallvec.workspace = true
zerocopy.workspace = true
event-listener.workspace = true

[lints]
workspace = true
