# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "netvsp_resources"
edition = "2021"
rust-version.workspace = true

[dependencies]
guid.workspace = true
mesh.workspace = true
net_backend_resources.workspace = true
vm_resource.workspace = true

[lints]
workspace = true
