# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "ide_resources"
edition = "2021"
rust-version.workspace = true

[dependencies]
scsidisk_resources.workspace = true
vm_resource.workspace = true

inspect.workspace = true
mesh.workspace = true

[lints]
workspace = true
