# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "fdt"
edition = "2021"
rust-version.workspace = true

[dependencies]
thiserror.workspace = true
zerocopy.workspace = true
zerocopy_helpers.workspace = true

[lints]
workspace = true
