# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "ucs2"
edition = "2021"
rust-version.workspace = true

[features]
mesh = ["mesh_protobuf"]

[dependencies]
mesh_protobuf = { workspace = true, optional = true }

thiserror.workspace = true

[lints]
workspace = true
