# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "inspect_derive"
edition = "2021"
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
heck.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn = { workspace = true, features = [ "extra-traits", "full" ] }

[lints]
workspace = true
