# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "petri_artifacts_common"
edition = "2021"
rust-version.workspace = true

[dependencies]
petri_artifacts_core.workspace = true

[lints]
workspace = true
