# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "page_table"
edition = "2021"
rust-version.workspace = true

[dependencies]
bitfield-struct.workspace = true
tracing.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
