# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "cvm_tracing"
edition = "2021"
rust-version.workspace = true

[dependencies]
tracing.workspace = true
tracing-subscriber.workspace = true

[lints]
workspace = true
