# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "flowey_trampoline"
edition = "2021"
rust-version.workspace = true

[dependencies]

[lints]
workspace = true
