# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "memory_range"
edition = "2021"
rust-version.workspace = true

[features]
inspect = ["dep:inspect"]
mesh = ["dep:mesh_protobuf"]

[dependencies]
inspect = { workspace = true, optional = true }
mesh_protobuf = { workspace = true, optional = true }

thiserror.workspace = true

[lints]
workspace = true
