# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vm_resource"
edition = "2021"
rust-version.workspace = true

[dependencies]
inspect.workspace = true
mesh.workspace = true
async-trait.workspace = true
linkme.workspace = true
thiserror.workspace = true

[dev-dependencies]
pal_async.workspace = true

[lints]
workspace = true
