# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "nvme_common"
edition = "2021"
rust-version.workspace = true

[dependencies]
disk_backend.workspace = true
nvme_spec.workspace = true

thiserror.workspace = true

[lints]
workspace = true
