# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "acpi"
edition = "2021"
rust-version.workspace = true

[dependencies]
acpi_spec.workspace = true
memory_range.workspace = true
x86defs.workspace = true

zerocopy.workspace = true

[lints]
workspace = true
