# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "igvmfilegen_config"
edition = "2021"
rust-version.workspace = true

[dependencies]
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
serde_json.workspace = true

[lints]
workspace = true
