# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "save_restore_derive"
edition = "2021"
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
quote.workspace = true
syn = { workspace = true, features = [ "extra-traits" ] }

[lints]
workspace = true
