# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "aarch64defs"
edition = "2021"
rust-version.workspace = true

[dependencies]
open_enum.workspace = true

bitfield-struct.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
