# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "linux_net_bindings"
edition = "2021"
rust-version.workspace = true

[target.'cfg(unix)'.dependencies]
nix = { workspace = true, features = ["ioctl"] }

[lints]
workspace = true
