# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "zerocopy_helpers"
edition = "2021"
rust-version.workspace = true

[dependencies]
zerocopy.workspace = true

[lints]
workspace = true
