# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "kmsg"
edition = "2021"
rust-version.workspace = true

[dependencies]
thiserror.workspace = true

[lints]
workspace = true
