# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "closeable_mutex"
edition = "2021"
rust-version.workspace = true

[dependencies]
parking_lot.workspace = true

[lints]
workspace = true
