# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "pci_bus"
edition = "2021"
rust-version.workspace = true

[dependencies]
chipset_device.workspace = true
vmcore.workspace = true

inspect.workspace = true
mesh.workspace = true

bitfield-struct.workspace = true
thiserror.workspace = true
tracelimit.workspace = true
tracing.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
