# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "pipette_protocol"
edition = "2021"
rust-version.workspace = true

[dependencies]
mesh.workspace = true

[lints]
workspace = true
