# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "guestmem"
edition = "2021"
rust-version.workspace = true

[dependencies]
inspect.workspace = true
pal_event.workspace = true
sparse_mmap.workspace = true

thiserror.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
