# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "term"
edition = "2021"
rust-version.workspace = true

[target.'cfg(windows)'.dependencies.winapi]
features = [
  "consoleapi",
  "handleapi",
  "memoryapi",
  "namedpipeapi",
  "processenv",
  "realtimeapiset",
  "synchapi",
  "winbase",
  "wincon",
  "winnls",
  "winnt",
  "winsock2",
]
workspace = true

[target.'cfg(unix)'.dependencies]
crossterm.workspace = true
libc.workspace = true

[lints]
workspace = true
