# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "underhill_confidentiality"
edition = "2021"
rust-version.workspace = true

[features]
std = []

[lints]
workspace = true
