# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "hyperv_ic_protocol"
edition = "2021"
rust-version.workspace = true

[dependencies]
guid.workspace = true

bitfield-struct.workspace = true
open_enum.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
