# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "win_prng_support"
edition = "2021"
rust-version.workspace = true

[target.'cfg(windows)'.dependencies]
widestring.workspace = true

[build-dependencies]
win_import_lib.workspace = true

[lints]
workspace = true
