# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "ci_logger"
edition = "2021"
rust-version.workspace = true

[dependencies]
env_logger.workspace = true
log.workspace = true

[lints]
workspace = true
