# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vmm_core_defs"
edition = "2021"
rust-version.workspace = true

[dependencies]
virt.workspace = true

inspect.workspace = true
mesh.workspace = true

[lints]
workspace = true
