# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "inspect_task"
edition = "2021"
rust-version.workspace = true

[dependencies]
inspect.workspace = true
pal_async.workspace = true

[lints]
workspace = true
