# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "chipset_device_resources"
edition = "2021"
rust-version.workspace = true

[dependencies]
chipset_device.workspace = true
guestmem.workspace = true
vmcore.workspace = true
vm_resource.workspace = true

inspect.workspace = true

async-trait.workspace = true

[lints]
workspace = true
