# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "kvm"
edition = "2021"
rust-version.workspace = true

[dependencies]
pal.workspace = true

[target.'cfg(unix)'.dependencies]
kvm-bindings.workspace = true
libc.workspace = true
nix = { workspace = true, features = ["ioctl"] }
parking_lot.workspace = true
signal-hook.workspace = true
thiserror.workspace = true

[lints]
workspace = true
