# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "sidecar_defs"
edition = "2021"
rust-version.workspace = true

[dependencies]
hvdef.workspace = true
open_enum.workspace = true
x86defs.workspace = true

zerocopy.workspace = true

[lints]
workspace = true
