# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "get_helpers"
edition = "2021"
rust-version.workspace = true

[dependencies]
get_protocol.workspace = true
guid.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
