# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "openssl_crypto_only"
edition = "2021"
rust-version.workspace = true

[dependencies]

[lints]
workspace = true
