# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vmbus_serial_protocol"
edition = "2021"
rust-version.workspace = true

[dependencies]
guid.workspace = true
open_enum.workspace = true

static_assertions.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
