# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vga_proxy"
edition = "2021"
rust-version.workspace = true

[dependencies]
inspect.workspace = true
chipset_device.workspace = true
vmcore.workspace = true

async-trait.workspace = true
tracelimit.workspace = true
tracing.workspace = true

[lints]
workspace = true
