# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "video_core"
edition = "2021"
rust-version.workspace = true

[dependencies]
inspect.workspace = true
mesh.workspace = true
vm_resource.workspace = true

async-trait.workspace = true

[lints]
workspace = true
