# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "gdma_defs"
edition = "2021"
rust-version.workspace = true

[dependencies]
guestmem.workspace = true

inspect.workspace = true
open_enum.workspace = true

bitfield-struct.workspace = true
zerocopy.workspace = true

[lints]
workspace = true
