# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "vhd1_defs"
edition = "2021"
rust-version.workspace = true

[dependencies]
guid.workspace = true

zerocopy.workspace = true

[lints]
workspace = true
