# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

[package]
name = "scsidisk_resources"
edition = "2021"
rust-version.workspace = true

[dependencies]
inspect.workspace = true
storage_string.workspace = true
vm_resource.workspace = true
mesh.workspace = true

[lints]
workspace = true
